import { type RecipeWithIngredients } from '@/types/database'

export const MOCK_RECIPES: RecipeWithIngredients[] = [
  {
    id: 'mock-pasta-courgette',
    title: 'Pates completes aux courgettes et ricotta',
    description: 'Un plat familial rapide, cremeux sans etre lourd, parfait pour un soir de semaine.',
    photo_url: '/images/recipes/dish-pates-courgettes.jpg',
    prep_time_minutes: 25,
    servings_base: 4,
    tags: ['vegetarian', 'quick', 'family'],
    season: ['spring', 'summer'],
    calories: 540,
    proteins_g: 22,
    carbs_g: 72,
    fats_g: 18,
    steps: [
      { step: 1, instruction: 'Cuire les pates dans une grande casserole d eau salee.' },
      { step: 2, instruction: 'Faire revenir les courgettes avec l ail et l huile d olive.' },
      { step: 3, instruction: 'Detendre la ricotta avec un peu d eau de cuisson et du citron.' },
      { step: 4, instruction: 'Assembler, ajouter le parmesan et servir avec du basilic.' },
    ],
    is_active: true,
    created_at: '2026-04-01T00:00:00.000Z',
    ingredients: [
      ingredient('mock-pasta-courgette', 'Pates completes', 360, 'g', 'epicerie'),
      ingredient('mock-pasta-courgette', 'Courgettes', 3, 'piece', 'legumes'),
      ingredient('mock-pasta-courgette', 'Ricotta', 250, 'g', 'produits laitiers'),
      ingredient('mock-pasta-courgette', 'Parmesan', 50, 'g', 'produits laitiers'),
      ingredient('mock-pasta-courgette', 'Citron', 1, 'piece', 'fruits'),
    ],
  },
  {
    id: 'mock-chicken-tray',
    title: 'Poulet au four, grenailles et carottes',
    description: 'Une plaque complete au four avec peu de vaisselle et des legumes bien rotis.',
    photo_url: '/images/recipes/dish-poulet-four.jpg',
    prep_time_minutes: 45,
    servings_base: 4,
    tags: ['family', 'high_protein', 'gluten_free'],
    season: ['autumn', 'winter'],
    calories: 610,
    proteins_g: 43,
    carbs_g: 48,
    fats_g: 24,
    steps: [
      { step: 1, instruction: 'Prechauffer le four a 200 degres.' },
      { step: 2, instruction: 'Melanger grenailles, carottes, huile, thym et paprika.' },
      { step: 3, instruction: 'Ajouter le poulet sur la plaque et enfourner.' },
      { step: 4, instruction: 'Retourner a mi-cuisson et servir bien dore.' },
    ],
    is_active: true,
    created_at: '2026-04-02T00:00:00.000Z',
    ingredients: [
      ingredient('mock-chicken-tray', 'Cuisses de poulet', 4, 'piece', 'viandes'),
      ingredient('mock-chicken-tray', 'Pommes de terre grenailles', 800, 'g', 'legumes'),
      ingredient('mock-chicken-tray', 'Carottes', 600, 'g', 'legumes'),
      ingredient('mock-chicken-tray', 'Huile d olive', 3, 'c. a soupe', 'epicerie'),
      ingredient('mock-chicken-tray', 'Thym', 1, 'c. a cafe', 'epicerie'),
    ],
  },
  {
    id: 'mock-chickpea-curry',
    title: 'Curry de pois chiches aux epinards',
    description: 'Un curry vegetal doux, nourrissant, pratique pour le batch cooking.',
    photo_url: '/images/recipes/dish-curry-pois-chiches.jpg',
    prep_time_minutes: 30,
    servings_base: 4,
    tags: ['vegan', 'vegetarian', 'gluten_free', 'batch_cooking'],
    season: ['autumn', 'winter', 'spring'],
    calories: 480,
    proteins_g: 18,
    carbs_g: 58,
    fats_g: 19,
    steps: [
      { step: 1, instruction: 'Faire revenir oignon, ail et gingembre.' },
      { step: 2, instruction: 'Ajouter curry, pois chiches et tomates concassees.' },
      { step: 3, instruction: 'Laisser mijoter avec le lait de coco.' },
      { step: 4, instruction: 'Ajouter les epinards et servir avec le riz.' },
    ],
    is_active: true,
    created_at: '2026-04-03T00:00:00.000Z',
    ingredients: [
      ingredient('mock-chickpea-curry', 'Pois chiches cuits', 500, 'g', 'epicerie'),
      ingredient('mock-chickpea-curry', 'Epinards', 250, 'g', 'legumes'),
      ingredient('mock-chickpea-curry', 'Tomates concassees', 400, 'g', 'epicerie'),
      ingredient('mock-chickpea-curry', 'Lait de coco', 250, 'ml', 'epicerie'),
      ingredient('mock-chickpea-curry', 'Riz basmati', 280, 'g', 'epicerie'),
    ],
  },
  {
    id: 'mock-salmon-bowl',
    title: 'Saumon laque, riz et brocoli',
    description: 'Un bol simple avec saumon fondant, sauce soja-miel et brocoli croquant.',
    photo_url: '/images/recipes/dish-saumon-laque.jpg',
    prep_time_minutes: 30,
    servings_base: 4,
    tags: ['quick', 'high_protein'],
    season: ['spring', 'winter'],
    calories: 590,
    proteins_g: 38,
    carbs_g: 62,
    fats_g: 20,
    steps: [
      { step: 1, instruction: 'Cuire le riz selon les indications du paquet.' },
      { step: 2, instruction: 'Melanger sauce soja, miel, ail et citron.' },
      { step: 3, instruction: 'Cuire le saumon et le napper de sauce.' },
      { step: 4, instruction: 'Servir avec le brocoli vapeur.' },
    ],
    is_active: true,
    created_at: '2026-04-04T00:00:00.000Z',
    ingredients: [
      ingredient('mock-salmon-bowl', 'Paves de saumon', 4, 'piece', 'poissons'),
      ingredient('mock-salmon-bowl', 'Riz jasmin', 280, 'g', 'epicerie'),
      ingredient('mock-salmon-bowl', 'Brocoli', 600, 'g', 'legumes'),
      ingredient('mock-salmon-bowl', 'Sauce soja', 4, 'c. a soupe', 'epicerie'),
      ingredient('mock-salmon-bowl', 'Miel', 2, 'c. a soupe', 'epicerie'),
    ],
  },
  {
    id: 'mock-lentil-salad',
    title: 'Salade tiede de lentilles, feta et betterave',
    description: 'Une assiette vegetarienne coloree qui tient bien au corps sans alourdir.',
    photo_url: '/images/recipes/dish-salade-lentilles.jpg',
    prep_time_minutes: 20,
    servings_base: 4,
    tags: ['vegetarian', 'quick', 'gluten_free', 'light'],
    season: ['autumn', 'winter'],
    calories: 430,
    proteins_g: 21,
    carbs_g: 42,
    fats_g: 18,
    steps: [
      { step: 1, instruction: 'Rechauffer les lentilles cuites.' },
      { step: 2, instruction: 'Couper les betteraves et emincer l oignon rouge.' },
      { step: 3, instruction: 'Preparer une vinaigrette moutarde et vinaigre.' },
      { step: 4, instruction: 'Assembler avec feta, persil et noix.' },
    ],
    is_active: true,
    created_at: '2026-04-05T00:00:00.000Z',
    ingredients: [
      ingredient('mock-lentil-salad', 'Lentilles cuites', 500, 'g', 'epicerie'),
      ingredient('mock-lentil-salad', 'Betteraves cuites', 400, 'g', 'legumes'),
      ingredient('mock-lentil-salad', 'Feta', 180, 'g', 'produits laitiers'),
      ingredient('mock-lentil-salad', 'Oignon rouge', 1, 'piece', 'legumes'),
      ingredient('mock-lentil-salad', 'Noix', 60, 'g', 'epicerie'),
    ],
  },
  {
    id: 'mock-omelette',
    title: 'Omelette aux champignons et salade croquante',
    description: 'Un repas express du soir, economique, avec des proteines et beaucoup de fraicheur.',
    photo_url: '/images/recipes/dish-omelette-champignons.jpg',
    prep_time_minutes: 18,
    servings_base: 4,
    tags: ['vegetarian', 'quick', 'gluten_free'],
    season: ['autumn', 'winter', 'spring'],
    calories: 390,
    proteins_g: 24,
    carbs_g: 14,
    fats_g: 27,
    steps: [
      { step: 1, instruction: 'Faire revenir les champignons tranches.' },
      { step: 2, instruction: 'Battre les oeufs avec le lait, sel et poivre.' },
      { step: 3, instruction: 'Cuire doucement jusqu a prise.' },
      { step: 4, instruction: 'Servir avec concombre et radis.' },
    ],
    is_active: true,
    created_at: '2026-04-06T00:00:00.000Z',
    ingredients: [
      ingredient('mock-omelette', 'Oeufs', 8, 'piece', 'produits laitiers'),
      ingredient('mock-omelette', 'Champignons', 400, 'g', 'legumes'),
      ingredient('mock-omelette', 'Lait', 80, 'ml', 'produits laitiers'),
      ingredient('mock-omelette', 'Concombre', 1, 'piece', 'legumes'),
      ingredient('mock-omelette', 'Radis', 1, 'botte', 'legumes'),
    ],
  },
  {
    id: 'mock-turkey-meatballs',
    title: 'Boulettes de dinde sauce tomate et polenta',
    description: 'Un plat reconfortant, riche en proteines, facile a rechauffer le lendemain.',
    photo_url: '/images/recipes/dish-boulettes-dinde.jpg',
    prep_time_minutes: 40,
    servings_base: 4,
    tags: ['family', 'high_protein', 'batch_cooking'],
    season: ['autumn', 'winter'],
    calories: 620,
    proteins_g: 42,
    carbs_g: 56,
    fats_g: 22,
    steps: [
      { step: 1, instruction: 'Melanger dinde hachee, chapelure, oeuf et herbes.' },
      { step: 2, instruction: 'Former les boulettes et les dorer.' },
      { step: 3, instruction: 'Ajouter la sauce tomate et mijoter.' },
      { step: 4, instruction: 'Servir avec polenta et parmesan.' },
    ],
    is_active: true,
    created_at: '2026-04-07T00:00:00.000Z',
    ingredients: [
      ingredient('mock-turkey-meatballs', 'Dinde hachee', 600, 'g', 'viandes'),
      ingredient('mock-turkey-meatballs', 'Chapelure', 60, 'g', 'epicerie'),
      ingredient('mock-turkey-meatballs', 'Oeuf', 1, 'piece', 'produits laitiers'),
      ingredient('mock-turkey-meatballs', 'Sauce tomate', 600, 'g', 'epicerie'),
      ingredient('mock-turkey-meatballs', 'Polenta', 250, 'g', 'epicerie'),
    ],
  },
  {
    id: 'mock-black-bean-tacos',
    title: 'Tacos haricots noirs, avocat et chou rouge',
    description: 'Des tacos vegetariens frais et rapides, parfaits pour un repas convivial.',
    photo_url: '/images/recipes/dish-tacos-haricots.jpg',
    prep_time_minutes: 25,
    servings_base: 4,
    tags: ['vegetarian', 'quick', 'family'],
    season: ['spring', 'summer'],
    calories: 510,
    proteins_g: 17,
    carbs_g: 68,
    fats_g: 19,
    steps: [
      { step: 1, instruction: 'Rechauffer les haricots avec cumin et tomate.' },
      { step: 2, instruction: 'Emincer le chou rouge et citronner.' },
      { step: 3, instruction: 'Ecraser l avocat avec citron vert et coriandre.' },
      { step: 4, instruction: 'Garnir les tortillas et servir.' },
    ],
    is_active: true,
    created_at: '2026-04-08T00:00:00.000Z',
    ingredients: [
      ingredient('mock-black-bean-tacos', 'Tortillas', 8, 'piece', 'boulangerie'),
      ingredient('mock-black-bean-tacos', 'Haricots noirs', 500, 'g', 'epicerie'),
      ingredient('mock-black-bean-tacos', 'Avocats', 2, 'piece', 'fruits'),
      ingredient('mock-black-bean-tacos', 'Chou rouge', 300, 'g', 'legumes'),
      ingredient('mock-black-bean-tacos', 'Yaourt grec', 150, 'g', 'produits laitiers'),
    ],
  },
  {
    id: 'mock-shakshuka',
    title: 'Shakshuka aux poivrons et pain grille',
    description: 'Des oeufs poches dans une sauce tomate epicee, parfaits pour un diner simple.',
    photo_url: '/images/recipes/dish-shakshuka.jpg',
    prep_time_minutes: 28,
    servings_base: 4,
    tags: ['vegetarian', 'quick', 'family'],
    season: ['spring', 'summer', 'autumn'],
    calories: 460,
    proteins_g: 23,
    carbs_g: 44,
    fats_g: 21,
    steps: [
      { step: 1, instruction: 'Faire revenir oignon et poivrons en lanieres.' },
      { step: 2, instruction: 'Ajouter tomates, cumin et paprika puis mijoter.' },
      { step: 3, instruction: 'Creuser quatre nids et casser les oeufs.' },
      { step: 4, instruction: 'Servir avec pain grille et coriandre.' },
    ],
    is_active: true,
    created_at: '2026-04-09T00:00:00.000Z',
    ingredients: [
      ingredient('mock-shakshuka', 'Oeufs', 8, 'piece', 'produits laitiers'),
      ingredient('mock-shakshuka', 'Poivrons', 3, 'piece', 'legumes'),
      ingredient('mock-shakshuka', 'Tomates concassees', 800, 'g', 'epicerie'),
      ingredient('mock-shakshuka', 'Oignon', 1, 'piece', 'legumes'),
      ingredient('mock-shakshuka', 'Pain complet', 1, 'piece', 'boulangerie'),
    ],
  },
  {
    id: 'mock-quinoa-bowl',
    title: 'Bowl quinoa, patate douce et halloumi',
    description: 'Un bowl vegetarien rassasiant avec legumes rotis et fromage grille.',
    photo_url: '/images/recipes/dish-quinoa-bowl.jpg',
    prep_time_minutes: 35,
    servings_base: 4,
    tags: ['vegetarian', 'gluten_free', 'family'],
    season: ['autumn', 'winter'],
    calories: 570,
    proteins_g: 25,
    carbs_g: 64,
    fats_g: 24,
    steps: [
      { step: 1, instruction: 'Rotir les patates douces au four avec paprika.' },
      { step: 2, instruction: 'Cuire le quinoa dans deux volumes d eau.' },
      { step: 3, instruction: 'Griller l halloumi a la poele.' },
      { step: 4, instruction: 'Assembler avec roquette, sauce yaourt et citron.' },
    ],
    is_active: true,
    created_at: '2026-04-10T00:00:00.000Z',
    ingredients: [
      ingredient('mock-quinoa-bowl', 'Quinoa', 280, 'g', 'epicerie'),
      ingredient('mock-quinoa-bowl', 'Patates douces', 700, 'g', 'legumes'),
      ingredient('mock-quinoa-bowl', 'Halloumi', 250, 'g', 'produits laitiers'),
      ingredient('mock-quinoa-bowl', 'Roquette', 120, 'g', 'legumes'),
      ingredient('mock-quinoa-bowl', 'Yaourt grec', 180, 'g', 'produits laitiers'),
    ],
  },
  ...buildAdditionalMockRecipes(),
]

export const CATALOG_ONLY_RECIPES: RecipeWithIngredients[] = buildCatalogOnlyMockRecipes()
export const CATALOG_RECIPES: RecipeWithIngredients[] = [...MOCK_RECIPES, ...CATALOG_ONLY_RECIPES]
export const WEEK_RECIPES: RecipeWithIngredients[] = MOCK_RECIPES.slice(0, 20)
export const PHOTO_CATALOG_RECIPES: RecipeWithIngredients[] = MOCK_RECIPES.filter(
  (recipe) => Boolean(recipe.photo_url) && recipe.photo_url !== '/images/recipes/dish-frittata-legumes.jpg'
)

export function filterMockRecipes(filters: {
  search?: string
  tag?: string
  season?: string
  maxTime?: number
  maxCalories?: number
}) {
  return PHOTO_CATALOG_RECIPES.filter((recipe) => {
    const matchesSearch = filters.search
      ? recipe.title.toLowerCase().includes(filters.search.toLowerCase())
      : true
    const matchesTag = filters.tag ? recipe.tags.includes(filters.tag) : true
    const matchesSeason = filters.season ? recipe.season.includes(filters.season) : true
    const matchesTime = filters.maxTime ? recipe.prep_time_minutes <= filters.maxTime : true
    const matchesCalories = filters.maxCalories ? (recipe.calories ?? 0) <= filters.maxCalories : true

    return matchesSearch && matchesTag && matchesSeason && matchesTime && matchesCalories
  })
}

function ingredient(
  recipeId: string,
  name: string,
  quantity: number,
  unit: string,
  groceryCategory: string
) {
  return {
    id: `${recipeId}-${name.toLowerCase().replaceAll(' ', '-')}`,
    recipe_id: recipeId,
    name,
    quantity,
    unit,
    grocery_category: groceryCategory,
  }
}

function buildAdditionalMockRecipes(): RecipeWithIngredients[] {
  const specs = [
    {
      id: 'mock-veloute-tomate',
      title: 'Veloute de tomates roties et feta',
      description: 'Une soupe douce et riche en legumes, avec une touche de feta pour le cote gourmand.',
      photo_url: '/images/recipes/dish-veloute-tomate.jpg',
      prep_time_minutes: 25,
      tags: ['vegetarian', 'quick', 'light'],
      season: ['summer', 'autumn'],
      calories: 360,
      proteins_g: 15,
      carbs_g: 34,
      fats_g: 18,
      ingredients: [
        ['Tomates', 900, 'g', 'legumes'],
        ['Feta', 160, 'g', 'produits laitiers'],
        ['Oignon rouge', 1, 'piece', 'legumes'],
        ['Pain complet', 4, 'tranches', 'boulangerie'],
      ],
    },
    {
      id: 'mock-wrap-poulet',
      title: 'Wrap poulet, crudites et sauce yaourt',
      description: 'Un repas frais, proteine et facile a emporter pour le midi.',
      photo_url: '/images/recipes/dish-wrap-poulet.jpg',
      prep_time_minutes: 20,
      tags: ['quick', 'family', 'high_protein'],
      season: ['spring', 'summer'],
      calories: 520,
      proteins_g: 39,
      carbs_g: 48,
      fats_g: 18,
      ingredients: [
        ['Blancs de poulet', 500, 'g', 'viandes'],
        ['Tortillas completes', 4, 'piece', 'boulangerie'],
        ['Yaourt grec', 180, 'g', 'produits laitiers'],
        ['Carottes rapees', 250, 'g', 'legumes'],
      ],
    },
    {
      id: 'mock-risotto-champignons',
      title: 'Risotto leger aux champignons',
      description: 'Un risotto cremeux mais equilibre, parfait avec une salade verte.',
      photo_url: '/images/recipes/dish-risotto-champignons.jpg',
      prep_time_minutes: 35,
      tags: ['vegetarian', 'family'],
      season: ['autumn', 'winter'],
      calories: 560,
      proteins_g: 18,
      carbs_g: 76,
      fats_g: 20,
      ingredients: [
        ['Riz arborio', 300, 'g', 'epicerie'],
        ['Champignons', 500, 'g', 'legumes'],
        ['Parmesan', 70, 'g', 'produits laitiers'],
        ['Bouillon de legumes', 900, 'ml', 'epicerie'],
      ],
    },
    {
      id: 'mock-cabillaud-citron',
      title: 'Cabillaud citron, haricots verts et quinoa',
      description: 'Une assiette legere avec poisson fondant, quinoa et legumes croquants.',
      photo_url: '/images/recipes/dish-cabillaud-citron.jpg',
      prep_time_minutes: 28,
      tags: ['quick', 'gluten_free', 'light'],
      season: ['spring', 'summer'],
      calories: 470,
      proteins_g: 36,
      carbs_g: 46,
      fats_g: 14,
      ingredients: [
        ['Dos de cabillaud', 4, 'piece', 'poissons'],
        ['Quinoa', 260, 'g', 'epicerie'],
        ['Haricots verts', 600, 'g', 'legumes'],
        ['Citron', 1, 'piece', 'fruits'],
      ],
    },
    {
      id: 'mock-buddha-bowl',
      title: 'Buddha bowl houmous, avocat et legumes',
      description: 'Un bol vegetal colore, rassasiant et plein de fibres.',
      photo_url: '/images/recipes/dish-buddha-bowl.jpg',
      prep_time_minutes: 22,
      tags: ['vegan', 'vegetarian', 'quick'],
      season: ['spring', 'summer'],
      calories: 540,
      proteins_g: 16,
      carbs_g: 62,
      fats_g: 24,
      ingredients: [
        ['Houmous', 220, 'g', 'epicerie'],
        ['Avocats', 2, 'piece', 'fruits'],
        ['Concombre', 1, 'piece', 'legumes'],
        ['Boulgour', 280, 'g', 'epicerie'],
      ],
    },
    {
      id: 'mock-chili-dinde',
      title: 'Chili de dinde aux haricots rouges',
      description: 'Un plat complet et reconfortant, riche en proteines et facile a rechauffer.',
      photo_url: '/images/recipes/dish-chili-dinde.jpg',
      prep_time_minutes: 38,
      tags: ['family', 'high_protein', 'batch_cooking'],
      season: ['autumn', 'winter'],
      calories: 610,
      proteins_g: 44,
      carbs_g: 54,
      fats_g: 20,
      ingredients: [
        ['Dinde hachee', 600, 'g', 'viandes'],
        ['Haricots rouges', 500, 'g', 'epicerie'],
        ['Tomates concassees', 600, 'g', 'epicerie'],
        ['Riz complet', 280, 'g', 'epicerie'],
      ],
    },
    {
      id: 'mock-gnocchis-epinards',
      title: 'Gnocchis epinards, ricotta et citron',
      description: 'Un plat vegetarien rapide avec une sauce fraiche et onctueuse.',
      photo_url: '/images/recipes/dish-gnocchis-epinards.jpg',
      prep_time_minutes: 18,
      tags: ['vegetarian', 'quick', 'family'],
      season: ['spring', 'winter'],
      calories: 580,
      proteins_g: 22,
      carbs_g: 78,
      fats_g: 18,
      ingredients: [
        ['Gnocchis', 700, 'g', 'epicerie'],
        ['Epinards', 300, 'g', 'legumes'],
        ['Ricotta', 220, 'g', 'produits laitiers'],
        ['Citron', 1, 'piece', 'fruits'],
      ],
    },
    {
      id: 'mock-salade-nicoise',
      title: 'Salade nicoise au thon et oeufs',
      description: 'Une grande salade complete, simple et ideale pour un repas frais.',
      photo_url: '/images/recipes/dish-salade-nicoise.jpg',
      prep_time_minutes: 24,
      tags: ['quick', 'gluten_free', 'high_protein'],
      season: ['spring', 'summer'],
      calories: 490,
      proteins_g: 34,
      carbs_g: 32,
      fats_g: 24,
      ingredients: [
        ['Thon', 280, 'g', 'poissons'],
        ['Oeufs', 6, 'piece', 'produits laitiers'],
        ['Pommes de terre', 600, 'g', 'legumes'],
        ['Haricots verts', 400, 'g', 'legumes'],
      ],
    },
    {
      id: 'mock-dahl-corail',
      title: 'Dahl de lentilles corail et riz basmati',
      description: 'Un classique vegetal, doux, sain et parfait pour le batch cooking.',
      photo_url: '/images/recipes/dish-dahl-corail.jpg',
      prep_time_minutes: 32,
      tags: ['vegan', 'vegetarian', 'batch_cooking'],
      season: ['autumn', 'winter'],
      calories: 520,
      proteins_g: 21,
      carbs_g: 74,
      fats_g: 16,
      ingredients: [
        ['Lentilles corail', 320, 'g', 'epicerie'],
        ['Lait de coco', 250, 'ml', 'epicerie'],
        ['Tomates concassees', 400, 'g', 'epicerie'],
        ['Riz basmati', 280, 'g', 'epicerie'],
      ],
    },
    {
      id: 'mock-brochettes-saumon',
      title: 'Brochettes de saumon, concombre et semoule',
      description: 'Une assiette fraiche, parfumee et rapide pour les beaux jours.',
      photo_url: '/images/recipes/dish-brochettes-saumon.jpg',
      prep_time_minutes: 26,
      tags: ['quick', 'high_protein', 'family'],
      season: ['spring', 'summer'],
      calories: 575,
      proteins_g: 37,
      carbs_g: 56,
      fats_g: 21,
      ingredients: [
        ['Saumon', 600, 'g', 'poissons'],
        ['Semoule complete', 280, 'g', 'epicerie'],
        ['Concombre', 1, 'piece', 'legumes'],
        ['Yaourt grec', 160, 'g', 'produits laitiers'],
      ],
    },
    {
      id: 'mock-frittata-legumes',
      title: 'Frittata legumes verts et chevre frais',
      description: 'Une recette simple pour vider le frigo avec des proteines et des legumes.',
      photo_url: '/images/recipes/dish-frittata-legumes.jpg',
      prep_time_minutes: 30,
      tags: ['vegetarian', 'gluten_free', 'family'],
      season: ['spring', 'summer'],
      calories: 430,
      proteins_g: 27,
      carbs_g: 18,
      fats_g: 28,
      ingredients: [
        ['Oeufs', 8, 'piece', 'produits laitiers'],
        ['Courgettes', 2, 'piece', 'legumes'],
        ['Petits pois', 250, 'g', 'surgeles'],
        ['Chevre frais', 160, 'g', 'produits laitiers'],
      ],
    },
    {
      id: 'mock-boulettes-vegetales',
      title: 'Boulettes vegetales, sauce tomate et couscous',
      description: 'Un plat familial sans viande, genereux et facile a preparer.',
      photo_url: '/images/recipes/dish-boulettes-vegetales.jpg',
      prep_time_minutes: 36,
      tags: ['vegetarian', 'family', 'batch_cooking'],
      season: ['autumn', 'winter'],
      calories: 590,
      proteins_g: 24,
      carbs_g: 82,
      fats_g: 18,
      ingredients: [
        ['Pois chiches', 450, 'g', 'epicerie'],
        ['Flocons d avoine', 90, 'g', 'epicerie'],
        ['Sauce tomate', 600, 'g', 'epicerie'],
        ['Couscous complet', 280, 'g', 'epicerie'],
      ],
    },
    {
      id: 'mock-poulet-coco',
      title: 'Poulet coco, courgettes et riz jasmin',
      description: 'Un plat doux et familial avec legumes, proteines et sauce legere.',
      photo_url: '/images/recipes/dish-poulet-coco.jpg',
      prep_time_minutes: 34,
      tags: ['family', 'high_protein', 'gluten_free'],
      season: ['spring', 'summer'],
      calories: 620,
      proteins_g: 41,
      carbs_g: 64,
      fats_g: 22,
      ingredients: [
        ['Blancs de poulet', 600, 'g', 'viandes'],
        ['Courgettes', 3, 'piece', 'legumes'],
        ['Lait de coco', 250, 'ml', 'epicerie'],
        ['Riz jasmin', 280, 'g', 'epicerie'],
      ],
    },
    {
      id: 'mock-soba-tofu',
      title: 'Nouilles soba, tofu croustillant et brocoli',
      description: 'Un repas vegetal complet avec une sauce soja-citron tres simple.',
      photo_url: '/images/recipes/dish-soba-tofu.jpg',
      prep_time_minutes: 27,
      tags: ['vegan', 'vegetarian', 'quick'],
      season: ['winter', 'spring'],
      calories: 550,
      proteins_g: 26,
      carbs_g: 68,
      fats_g: 19,
      ingredients: [
        ['Nouilles soba', 300, 'g', 'epicerie'],
        ['Tofu ferme', 400, 'g', 'epicerie'],
        ['Brocoli', 600, 'g', 'legumes'],
        ['Sauce soja', 4, 'c. a soupe', 'epicerie'],
      ],
    },
    {
      id: 'mock-tartines-avocat',
      title: 'Tartines avocat, oeuf et salade croquante',
      description: 'Une option express pour un repas simple, sain et rassasiant.',
      photo_url: '/images/recipes/dish-tartines-avocat.jpg',
      prep_time_minutes: 15,
      tags: ['vegetarian', 'quick', 'light'],
      season: ['spring', 'summer'],
      calories: 450,
      proteins_g: 20,
      carbs_g: 42,
      fats_g: 23,
      ingredients: [
        ['Pain complet', 8, 'tranches', 'boulangerie'],
        ['Avocats', 2, 'piece', 'fruits'],
        ['Oeufs', 4, 'piece', 'produits laitiers'],
        ['Salade', 160, 'g', 'legumes'],
      ],
    },
  ]

  return specs.map((spec, index) => ({
    ...spec,
    servings_base: 4,
    steps: [
      { step: 1, instruction: 'Preparer et couper les ingredients.' },
      { step: 2, instruction: 'Cuire les elements principaux selon le temps indique.' },
      { step: 3, instruction: 'Assembler avec la sauce ou les aromates.' },
      { step: 4, instruction: 'Rectifier l assaisonnement et servir.' },
    ],
    is_active: true,
    created_at: `2026-04-${String(11 + index).padStart(2, '0')}T00:00:00.000Z`,
    ingredients: spec.ingredients.map(([name, quantity, unit, category]) =>
      ingredient(spec.id, String(name), Number(quantity), String(unit), String(category))
    ),
  }))
}

function buildCatalogOnlyMockRecipes(): RecipeWithIngredients[] {
  const specs = [
    ['catalog-aubergines-miso', 'Aubergines miso, riz et concombre', 'Un bol vegetal savoureux avec aubergines fondantes, riz et fraicheur.', '/images/recipes/dish-salade-lentilles.jpg', 30, ['vegan', 'vegetarian', 'gluten_free'], ['summer', 'autumn'], 510, 16, 68, 18],
    ['catalog-poulet-moutarde', 'Poulet moutarde, poireaux et pommes vapeur', 'Un plat familial simple, equilibre et tres facile a remettre au menu.', '/images/recipes/dish-poulet-four.jpg', 35, ['family', 'high_protein', 'gluten_free'], ['autumn', 'winter'], 560, 42, 42, 22],
    ['catalog-taboule-quinoa', 'Taboule de quinoa, pois chiches et herbes', 'Une salade complete, fraiche et pratique pour les lunchs.', '/images/recipes/dish-salade-lentilles.jpg', 18, ['vegan', 'vegetarian', 'quick', 'gluten_free'], ['spring', 'summer'], 480, 17, 60, 18],
    ['catalog-pates-thon', 'Pates au thon, tomates et olives', 'Un diner express avec placard malin, proteines et legumes.', '/images/recipes/dish-pates-courgettes.jpg', 20, ['quick', 'family'], ['spring', 'summer'], 590, 34, 76, 18],
    ['catalog-tofu-cajou', 'Tofu cajou, brocoli et riz complet', 'Une assiette vegetale croustillante, riche en fibres et en gout.', '/images/recipes/dish-salade-lentilles.jpg', 28, ['vegan', 'vegetarian', 'high_protein'], ['winter', 'spring'], 610, 28, 66, 24],
    ['catalog-saumon-fenouil', 'Saumon au fenouil et pommes de terre', 'Un repas sain avec poisson, legumes rotis et citron.', '/images/recipes/dish-saumon-laque.jpg', 32, ['high_protein', 'gluten_free', 'family'], ['spring', 'winter'], 600, 39, 48, 25],
    ['catalog-galette-sarrasin', 'Galettes de sarrasin oeuf, epinards et fromage', 'Une option sans gluten rapide et rassasiante pour le soir.', '/images/recipes/dish-omelette-champignons.jpg', 22, ['vegetarian', 'quick', 'gluten_free'], ['autumn', 'winter'], 520, 25, 54, 22],
    ['catalog-soupe-lentilles', 'Soupe de lentilles vertes et carottes', 'Une soupe complete, economique et parfaite pour le batch cooking.', '/images/recipes/dish-curry-pois-chiches.jpg', 40, ['vegan', 'vegetarian', 'batch_cooking'], ['autumn', 'winter'], 430, 22, 58, 10],
    ['catalog-bowl-boeuf', 'Bowl boeuf, riz, carottes et sauce sesame', 'Un bowl complet avec proteines, cereales et legumes croquants.', '/images/recipes/dish-poulet-four.jpg', 26, ['high_protein', 'family'], ['spring', 'autumn'], 650, 41, 70, 23],
    ['catalog-croquettes-pois', 'Croquettes de pois chiches et salade yaourt', 'Une recette vegetarienne croustillante avec une sauce fraiche.', '/images/recipes/dish-tacos-haricots.jpg', 34, ['vegetarian', 'family'], ['spring', 'summer'], 560, 21, 64, 22],
    ['catalog-crevettes-coco', 'Crevettes coco, riz et petits legumes', 'Un plat rapide, parfume et leger pour varier les proteines.', '/images/recipes/dish-saumon-laque.jpg', 24, ['quick', 'gluten_free', 'high_protein'], ['spring', 'summer'], 540, 35, 58, 18],
    ['catalog-patate-chili', 'Patates douces farcies chili vegetarien', 'Des patates douces garnies, colorees et tres rassasiantes.', '/images/recipes/dish-tacos-haricots.jpg', 42, ['vegetarian', 'gluten_free', 'family'], ['autumn', 'winter'], 610, 22, 84, 18],
    ['catalog-ramen-poulet', 'Ramen poulet, champignons et oeuf mollet', 'Un bol reconfortant avec bouillon, nouilles et proteines.', '/images/recipes/dish-omelette-champignons.jpg', 36, ['family', 'high_protein'], ['winter', 'spring'], 640, 38, 72, 20],
    ['catalog-salade-poulet', 'Salade poulet grille, avocat et mangue', 'Une salade sucree-salee, fraiche et riche en proteines.', '/images/recipes/dish-salade-lentilles.jpg', 21, ['quick', 'gluten_free', 'high_protein'], ['spring', 'summer'], 520, 36, 38, 24],
    ['catalog-polenta-ratatouille', 'Polenta cremeuse et ratatouille express', 'Un plat vegetarien doux avec beaucoup de legumes.', '/images/recipes/dish-curry-pois-chiches.jpg', 30, ['vegetarian', 'gluten_free', 'family'], ['summer', 'autumn'], 500, 16, 68, 16],
    ['catalog-burger-saumon', 'Burger de saumon, salade et sauce citron', 'Une version plus saine du burger avec poisson et crudites.', '/images/recipes/dish-saumon-laque.jpg', 29, ['family', 'high_protein'], ['spring', 'summer'], 630, 37, 58, 27],
    ['catalog-wok-legumes', 'Wok de legumes, nouilles et sauce gingembre', 'Un wok rapide, vegetal et plein de couleurs.', '/images/recipes/dish-salade-lentilles.jpg', 19, ['vegan', 'vegetarian', 'quick'], ['spring', 'summer'], 470, 14, 72, 12],
    ['catalog-clafoutis-courgette', 'Clafoutis courgette, feta et menthe', 'Un repas vegetarien simple avec salade verte.', '/images/recipes/dish-pates-courgettes.jpg', 33, ['vegetarian', 'family'], ['summer'], 460, 23, 34, 26],
    ['catalog-tajine-poulet', 'Tajine poulet, abricots et semoule complete', 'Un plat familial parfume avec une touche sucree salee.', '/images/recipes/dish-poulet-four.jpg', 45, ['family', 'high_protein'], ['autumn', 'winter'], 670, 43, 78, 20],
    ['catalog-salade-riz', 'Salade de riz complet, thon et crudites', 'Une salade pratique, saine et facile a preparer en avance.', '/images/recipes/dish-salade-lentilles.jpg', 20, ['quick', 'gluten_free'], ['spring', 'summer'], 530, 29, 62, 18],
    ['catalog-lasagnes-legumes', 'Lasagnes legeres aux legumes et ricotta', 'Une version plus douce des lasagnes avec beaucoup de legumes.', '/images/recipes/dish-pates-courgettes.jpg', 50, ['vegetarian', 'family'], ['autumn', 'winter'], 620, 28, 72, 22],
    ['catalog-oeufs-tomate', 'Oeufs tomates, pois chiches et epices douces', 'Une poelee rapide et nourrissante inspiree de la shakshuka.', '/images/recipes/dish-omelette-champignons.jpg', 23, ['vegetarian', 'quick', 'gluten_free'], ['spring', 'autumn'], 470, 24, 42, 22],
    ['catalog-porc-ananas', 'Emince de porc, ananas et riz saute', 'Un plat familial colore avec une sauce legere.', '/images/recipes/dish-poulet-four.jpg', 27, ['family', 'high_protein'], ['spring', 'summer'], 640, 39, 74, 20],
    ['catalog-curry-legumes', 'Curry vert de legumes et tofu', 'Un curry vegetal rapide, cremeux et plein de legumes.', '/images/recipes/dish-curry-pois-chiches.jpg', 29, ['vegan', 'vegetarian', 'quick', 'gluten_free'], ['spring', 'summer'], 560, 24, 54, 26],
    ['catalog-sardines-pommes', 'Sardines grillees, pommes vapeur et salade', 'Un repas economique, riche en omega-3 et tres simple.', '/images/recipes/dish-saumon-laque.jpg', 25, ['quick', 'gluten_free', 'high_protein'], ['summer'], 520, 35, 38, 25],
    ['catalog-bowl-grec', 'Bowl grec, poulet, concombre et tzatziki', 'Un bol frais avec proteines, crudites et sauce yaourt.', '/images/recipes/dish-poulet-four.jpg', 24, ['quick', 'high_protein', 'family'], ['spring', 'summer'], 590, 42, 50, 22],
    ['catalog-couscous-vegetal', 'Couscous vegetal aux pois chiches', 'Un plat genereux, riche en legumes et facile a partager.', '/images/recipes/dish-tacos-haricots.jpg', 38, ['vegan', 'vegetarian', 'family'], ['autumn', 'winter'], 580, 19, 86, 14],
    ['catalog-courgettes-farcies', 'Courgettes farcies quinoa et feta', 'Des legumes farcis legers avec cereales et fromage frais.', '/images/recipes/dish-pates-courgettes.jpg', 40, ['vegetarian', 'gluten_free'], ['summer'], 510, 21, 58, 20],
    ['catalog-poke-truite', 'Poke bowl truite fumee, riz et edamame', 'Un bol frais, proteine et pret en moins de 25 minutes.', '/images/recipes/dish-saumon-laque.jpg', 22, ['quick', 'gluten_free', 'high_protein'], ['spring', 'summer'], 610, 34, 68, 22],
    ['catalog-curry-dinde', 'Curry doux de dinde et legumes croquants', 'Un curry familial rapide avec une sauce legere au yaourt.', '/images/recipes/dish-poulet-four.jpg', 31, ['family', 'high_protein', 'gluten_free'], ['autumn', 'winter'], 570, 43, 48, 20],
  ] as const

  return specs.map(([id, title, description, photo_url, prep_time_minutes, tags, season, calories, proteins_g, carbs_g, fats_g], index) => {
    const tagList = [...tags] as string[]
    const seasonList = [...season] as string[]
    const isPlantBased = tagList.includes('vegetarian') || tagList.includes('vegan')

    return {
      id,
      title,
      description,
      photo_url,
      prep_time_minutes,
      servings_base: 4,
      tags: tagList,
      season: seasonList,
      calories,
      proteins_g,
      carbs_g,
      fats_g,
      steps: [
        { step: 1, instruction: 'Preparer les legumes et les elements principaux.' },
        { step: 2, instruction: 'Cuire selon les temps indiques en gardant les textures.' },
        { step: 3, instruction: 'Assembler avec la sauce et ajuster l assaisonnement.' },
        { step: 4, instruction: 'Servir avec une portion adaptee au foyer.' },
      ],
      is_active: true,
      created_at: `2026-05-${String(1 + index).padStart(2, '0')}T00:00:00.000Z`,
      ingredients: [
        ingredient(id, 'Legumes de saison', 600, 'g', 'legumes'),
        ingredient(id, isPlantBased ? 'Proteine vegetale' : 'Proteine principale', 400, 'g', isPlantBased ? 'epicerie' : 'viandes'),
        ingredient(id, 'Base cerealiere', 280, 'g', 'epicerie'),
        ingredient(id, 'Sauce maison', 120, 'g', 'epicerie'),
      ],
    }
  })
}
